# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a6e13e7eaf8b0af5152e73e9f577da5d51f8d963570ab02a2a39e3baf804dd795dec293479b35fde771117ea8a6a1a98675856ca4d0441d2405ff0229b8477

test:
  secret_key_base: e510c09749e54356421ab491668cc4e4b138499b9e322ddbb963462b6431bce5b0aa1c2aaaa9b0a63952e3423d519c2e767ed1352661a07dfc7167feabad5144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
